config/routes.rb
AuctionLog::Application.routes.draw do

  resources :sales, :items
 
  match 'index', to: 'sales_list#index', via: 'get'
  match 'sales', to: 'sales#index', via: 'get'
  match 'items', to: 'items#index', via: 'get'

  root 'sales_list#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates :item_name, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def new
		@item = Item.new
	end

	def create
		@item = Item.new(params[:item].permit(:name))

		if @item.save
			redirect_to items_path
		else
			render 'new'
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def index
		@item = Item.all
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])

		if @item.update(params[:item].permit(:name))
			redirect_to items_path
		else
			render 'edit'
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		redirect_to items_path
	end


	private
		def item_params
			params.require(:item).permit(:name)
		end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def new
		@sale = Sale.new
	end

	def create
		@sale = Sale.new(params[:sale].permit(:item_name, :sold_price, :date, :quality))

		if @sale.save
			redirect_to sales_path
		else
			render 'new'
		end
	end

	def show
		@sale = Sale.find(params[:id])
	end

	def index
		@sale = Sale.limit(20).order('id DESC')
	end

	def edit
		@sale = Sale.find(params[:id])
	end

	def update
		@sale = Sale.find(params[:id])

		if @sale.update(params[:sale].permit(:item_name, :sold_price, :date, :quality))
			redirect_to sales_path
		else
			render 'edit'
		end
	end

	def destroy
		@sale = Sale.find(params[:id])
		@sale.destroy

		redirect_to sales_path
	end


	private
		def sale_params
			params.require(:sale).permit(:item_name, :sold_price, :date, :quality)
		end

end

app/controllers/sales_list_controller.rb
class SalesListController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sales_list_helper.rb
module SalesListHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
	<% if @item.errors.any? %>
		<div id="errorExplanaation">
			<h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved: 
			</h2>
			<ul>
				<% @item.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<table>
		<tr>
			<td><%= f.label :'id' %></td>
			<td><%= f.number_field :id, :readonly => true %></td>
		</tr>
		<tr>
			<td><%= f.label :"Item Name" %></td>
			<td><%= f.text_field :name, size: 30 %></td>
		</tr>
	</table>
	<p>
		<%= f.submit %> <%= button_to 'Cancel', items_path, :method => :get %>
	</p>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="pageBody">

	<table class='basicTable'>
		<tr>
			<th class='dataColumn'>Item Name</th>
			<th class='dataColumn'>   </th>
			<th class='buttonColumn'></th>
			<th class='buttonColumn'></th>
			<th class='buttonColumn'></th>
		</tr>

		<% @item.each do |item| %>
			<tr>
				<td class='dataColumn'><%= item.name %></td>
				<td class='dataColumn'></th>
				<td class='buttonColumn'><div class='button'><%= link_to 'Show', item_path(item) %></div></td>
				<td class='buttonColumn'><div class='button'><%= link_to 'Edit', edit_item_path(item) %></div></td>
				<td class='buttonColumn'><div class='button'><%= link_to 'Destroy', item_path(item), method: :delete, data: {confirm: 'Are you sure?' } %></div></td>
			</tr>
		<% end %>
		<tr><td colspan=9><div class='newItemTableBottom'>
			<span class='button bigbutton'><%= link_to "+ New item", new_item_path %></span>
		</div></td></tr>
	</table>
	
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market Auction History</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id='navBar'>
		<h1>
			Market Auction History
		</h1>
		<!-- <div><%= link_to 'Home', sales_path %></div> -->
		<span class="navElement"><%= link_to 'Sales', sales_path %></span>
		<span class="navElement"><%= link_to 'Items', items_path %></span>

	</div>

<%= yield %>

	<div class='footer'>
		<span id='footerText'><p>&copy;Nick Sanders Productions</p></span>
	</div>

</body>
</html>

app/views/sales/_form.html.erb
<%= form_for @sale do |f| %>
	<% if @sale.errors.any? %>
		<div id="errorExplanaation">
			<h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved: 
			</h2>
			<ul>
				<% @sale.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<table>
		<tr>
			<td><%= f.label :'id' %></td>
			<td><%= f.number_field :id, :readonly => true %></td>
		</tr>
		<tr>
			<td><%= f.label :"Quantity" %></td>
			<td><%= f.number_field :qty %></td>
		</tr>
		<tr>
			<td><%= f.label :"Item Name" %></td>
			<td><%= f.text_field :item_name, size: 30 %></td>
		</tr>
		<tr>
			<td><%= f.label :'Sold Price' %></td>
			<td><%= f.number_field :sold_price %></td>
		</tr>
		<tr>
			<td><%= f.label :'Quality' %></td>
			<td><%= f.number_field :quality %></td>
		</tr>
		<tr>
			<td><%= f.label :'Date' %></td>
			<td><%= f.date_select :date %></td>
		</tr>
	</table>

	<p>
		<%= f.submit %> <%= button_to 'Cancel', sales_path, :method => :get %>
	</p>
<% end %>

app/views/sales/edit.html.erb
<h1>Edit Sale</h1>
 
<%= render 'form' %>

app/views/sales/index.html.erb
<div class="pageBody">

	<table class='basicTable'>
		<tr>
			<th class='dataColumn'>Qty.</th>
			<th class='dataColumn'>Item Name</th>
			<th class='dataColumn'>Sold Price</th>
			<th class='dataColumn'>Quality</th>
			<th class='dataColumn'>Date</th>
			<th class='dataColumn'>   </th>
			<th class='buttonColumn'></th>
			<th class='buttonColumn'></th>
			<th class='buttonColumn'></th>
		</tr>

		<% @sale.each do |sale| %>
			<tr>
				<td class='dataColumn columnRight'><%= sale.qty %></td>
				<td class='dataColumn'><%= sale.item_name %></td>
				<td class='dataColumn columnRight'><%= sale.sold_price %></td>
				<td class='dataColumn columnRight'><%= sale.quality %></td>
				<td class='dataColumn'><%= sale.date %></td>
				<td class='dataColumn'></th>
				<td class='buttonColumn'><div class='button'><%= link_to 'Show', sale_path(sale) %></div></td>
				<td class='buttonColumn'><div class='button'><%= link_to 'Edit', edit_sale_path(sale) %></div></td>
				<td class='buttonColumn'><div class='button'><%= link_to 'Destroy', sale_path(sale), method: :delete, data: {confirm: 'Are you sure?' } %></div></td>
			</tr>
		<% end %>
		<tr><td colspan=9><div class='newItemTableBottom'>
			<span class='button bigbutton'><%= link_to "+ New Sale", new_sale_path %></span>
		</div></td></tr>
	</table>
	
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

app/views/sales/show.html.erb
<p>
	<strong>Item Name:</strong>
	<%= @sale.item_name %>
</p>

<p>
	<strong>Sold Price:</strong>
	<%= @sale.sold_price %>
</p>

<%= link_to 'Back', sales_path %> 
<%= link_to 'Edit', edit_sale_path(@sale) %>

app/views/sales_list/index.html.erb
<h1>SalesList#index</h1>
<p>Find me in app/views/sales_list/index.html.erb</p>
<p><%= link_to "My Sales", controller: "sales" %></p>